export const COUPON_LIST_REQUEST = "COUPON_LIST_REQUEST"
export const COUPON_LIST_SUCCESS = "COUPON_LIST_SUCCESS"
export const COUPON_LIST_FAIL = "COUPON_LIST_FAIL"

export const COUPON_DETAILS_REQUEST = "COUPON_DETAILS_REQUEST"
export const COUPON_DETAILS_SUCCESS = "COUPON_DETAILS_SUCCESS"
export const COUPON_DETAILS_FAIL = "COUPON_DETAILS_FAIL"

// export const COUPON_CREATE_REVIEW_REQUEST = "COUPON_CREATE_REVIEW_REQUEST"
// export const COUPON_CREATE_REVIEW_SUCCESS = "COUPON_CREATE_REVIEW_SUCCESS"
// export const COUPON_CREATE_REVIEW_FAIL = "COUPON_CREATE_REVIEW_FAIL"
// export const COUPON_CREATE_REVIEW_RESET = "COUPON_CREATE_REVIEW_RESET"